# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest', depending on your platform

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you need
    addToPath: true

- script: |
    python --version
    pip --version
    echo "Python and Pip installed successfully"
  displayName: 'Verify Python Installation'
