trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Pull the secret from Azure Key Vault
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'AzureVault'
    KeyVaultName: 'TestDemoValut'
    SecretsFilter: '*'
    RunAsPreJob: false

# 2. Print out the secret in the pipeline logs
- script: |
    echo "The secret value is: $(Demo12)"
  displayName: 'Print Secret Demo12'