name: Demo
on: [push, workflow_dispatch]
jobs:
  DemoOnPerfecto1:
    runs-on: ubuntu-latest
    steps:
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '17'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test
        run: mvn clean install test -Dreportium-job-name=${{ github.job }} -Dreportium-job-number=${{ github.run_number }}
  DemoOnPerfecto2:
    runs-on: ubuntu-latest
    steps:
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '17'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test
        run: mvn clean install test -Dreportium-job-name=${{ github.job }} -Dreportium-job-number=${{ github.run_number }}
