name: Scenario 1
on: push
jobs:
  testOnPerfecto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Run test
        run: mvn clean install test -Dreportium-job-name=${{ github.job }} -Dreportium-job-number=${{ github.run_number }}
      - name: Retrieve Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: allure-results
  testOnPerfecto1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Run test
        run: mvn clean install test -Dreportium-job-name=${{ github.job }} -Dreportium-job-number=${{ github.run_number }} -Dsurefire.suiteXmlFiles=src/main/resources/config/testng_appium.xml

      - name: Retrieve Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: allure-results