name: Scenario 1
on: [workflow_dispatch]
env:
  security_token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyODhhNDIyNS1jOTE1LTQwZDctOTc2YS04MDhiMWE3YTFmODYifQ.eyJpYXQiOjE3MzEwOTAzMTksImp0aSI6IjVlMzIxNzkzLTA4MTAtNGRmOS05Mjc4LTVkZDBjMGIwZTFiZiIsImlzcyI6Imh0dHBzOi8vYXV0aC5wZXJmZWN0b21vYmlsZS5jb20vYXV0aC9yZWFsbXMvcHMtcGVyZmVjdG9tb2JpbGUtY29tIiwiYXVkIjoiaHR0cHM6Ly9hdXRoLnBlcmZlY3RvbW9iaWxlLmNvbS9hdXRoL3JlYWxtcy9wcy1wZXJmZWN0b21vYmlsZS1jb20iLCJzdWIiOiI3YzAyMTU5ZC0zNjNmLTQ2ZDUtYjcyMS1hYjY1MGFlYzQ3ODQiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoib2ZmbGluZS10b2tlbi1nZW5lcmF0b3IiLCJub25jZSI6Ijc2MjcyMDE4LWYxYjYtNDBhYS04OTQwLTVmZjRjMjA0ZTZlOSIsInNlc3Npb25fc3RhdGUiOiIxZjhkMjdjMi0xYzgxLTQ3NGQtODgxNC0wYmY0Y2QyNzdhMzMiLCJzY29wZSI6Im9wZW5pZCBvZmZsaW5lX2FjY2VzcyIsInNpZCI6IjFmOGQyN2MyLTFjODEtNDc0ZC04ODE0LTBiZjRjZDI3N2EzMyJ9.3MyoJA8Yd-iyKQtJgKTCnUhXB2cE3dHS3opeUl-Yajg
jobs:
  testOnPerfecto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test
        run: mvn clean install test -Dreportium-job-name=${{ github.job }} -Dreportium-job-number=${{ github.run_number }} -Dperfecto.capabilities.securityToken=${{ env.security_token }}
      - name: Retrieve Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: allure-results
