name: Scenario 1
on: push
jobs:
  testOnPerfecto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Run test
        run: mvn clean install test -Dreportium-job-name=${{ github.job }} -Dreportium-job-number=${{ github.run_number }}
      - name: Retrieve Artifacts
        run: actions/upload-artifacts@v4
        with:
          name: artifacts
          path: allure-results