name: Scenario 1
on: push
jobs:
  testOnPerfecto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install JAVA
        run: java --version      
      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
      - name: Run test
        run: python --version
